server{
    listen 80;
    client_max_body_size 50M;
        # Tăng thời gian chờ Backend xử lý (VD: 300 giây = 5 phút)
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    proxy_read_timeout 300;
    send_timeout 300;
    location /{
       proxy_pass http://web:8080;
       proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Port 8005;
    }
}